<#--
Copyright (c) 2011, Cornell University
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
      this list of conditions and the following disclaimer in the documentation
      and/or other materials provided with the distribution.
    * Neither the name of Cornell University nor the names of its contributors
      may be used to endorse or promote products derived from this software
      without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<@widget name="login" include="assets" />
<#include "browse-classgroups.ftl">

<!DOCTYPE html>
<html lang="en">
    <head>
        <#include "head.ftl">
		<style>
		#background-wrapper {
			background-position: left 500px;
			background-repeat: repeat-x;
		}
		
		#wrapper-content {
			background: transparent !important;
		}
		</style>
    </head>
    
    <body class="${bodyClasses!}">
        <#include "identity.ftl">
        
        <#include "menu.ftl">
		
		<div id="home-middle-col" class="id-8451">
			<div id="home-bg-area">
				<#if env == "scf">
					<div class='home-bg-banner home-bg-banner-image-scf'>
				<#elseif env == "spatial">
					<div class='home-bg-banner home-bg-banner-image-spatial'>
				<#else>
					<div class='home-bg-banner home-bg-banner-image'>
				</#if>
					<div class="home-overlay"></div>
					<div class="home-content-holder">
						<#if env?? && env == "scf">
							<div class="quick-links">
								<ul>
									<li><a href="/">Research Data Finder</a></li>
									<li><a href="/scf" class="selected">Software Finder</a></li>
									<li><a href="/spatial">Spatial Data Finder</a></li>
								</ul>
							</div>
							<div class="home-content">
									Software & Code Finder is your key to <br/>
									locating software and source code <br/>
									generated by QUT researchers.<br/>
									<a href="/softwareAndCode" class="more"><span></span>Search</a><br/>
							</div>
						<#elseif env?? && env == "spatial">
							<div class="quick-links">
								<ul>
									<li><a href="/">Research Data Finder</a></li>
									<li><a href="/scf">Software Finder</a></li>
									<li><a href="/spatial" class="selected">Spatial Data Finder</a></li>
								</ul>
							</div>
							<div class="home-content">
									Spatial Data Finder is your key to locating <br/>
									spatially integrated data sets across <br/> 
									different areas of research.<br/>
									<a href="/spatialData" class="more"><span></span>Search</a><br/>
							</div>
						<#else>
							<div class="quick-links">
								<ul>
									<li><a href="/" class="selected">Research Data Finder</a></li>
									<li><a href="/scf">Software Finder</a></li>
									<li><a href="/spatial">Spatial Data Finder</a></li>
								</ul>
							</div>
							<div class="home-content">
								Research Data Finder is QUT's discovery <br/>
								service for research data created <br/>
								by QUT researchers.<br/>
								
								<a href="/dataCollections" class="more"><span></span>Search</a><br/>
								<#--
								<span style="background-color:#" class="heading">QUT Research Data Finder</span>
								-->
							</div>
							
						</#if>
					</div>
				

				
<div class="promo-carousel no-scroll">
<ul>
<#if env?? && env == "rdf">
	<li rel="/themes/qut/images/people.jpg" class="position-1 0 Yes" id="promo-id-245427">

		<a class="thumb normal" href="/services" title="Software and Equipment that have generated research data"></a>
		<img src="/themes/qut/images/services.jpg" width="220" height="105" alt=""> 
		<span>Equipment & Services</span> 
	  
	  <div class="promo-content-holder hide">
		  <p class="promo-content 0">
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/activities.jpg" class="position-2 0 Yes" id="promo-id-264677"> 

	  <a class="thumb normal" href="/activities" title="Research Projects that have generated research datasets"></a>
	  
		<img src="/themes/qut/images/activities.jpg" width="220" height="105" alt=""> 
		<span>Projects</span> 
		

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/collections.jpg" class="position-3 0 Yes" id="promo-id-264874"> 

	<a class="thumb normal" href="/people#http://www.qut.edu.au/ontologies/vivoqut#researcher" title="People and Groups that have generated research datasets"></a>
		 <img src="/themes/qut/images/people.jpg" width="220" height="105" alt=""> 
		 <span>People & Groups</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/services.jpg" class="position-4 0 Yes" id="promo-id-266134"> 
	
	<a class="thumb normal" href="/dataCollections" title="Data Collections created or collected by QUT researchers"></a>
		<img src="/themes/qut/images/collections.jpg" width="220" height="105" alt=""> 
		<span>Data Collections</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
</ul>
</#if>
<#--  
<ul>

<#if env?? && env == "scf">
	<li rel="/themes/qut/images/rdf-home-small.jpg" class="position-1 0 Yes" id="promo-id-245427">

	  <a class="thumb normal" href="/" title="Research Data Finder"></a>
		 <img src="/themes/qut/images/rdf-home-small.jpg" width="220" height="105" alt=""> 
		 <span>Research Data Finder</span> 
	  
	  <div class="promo-content-holder hide">
		  <p class="promo-content 0">
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/spatial-home-small.jpg" class="position-2 0 Yes" id="promo-id-264677"> 

	  <a class="thumb normal" href="/spatial" title="Spatial Data Finder"></a>
	  
		<img src="/themes/qut/images/spatial-home-small.jpg" width="220" height="105" alt=""> 
		<span>Spatial Data Finder</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
<#elseif  env?? && env == "spatial">
	<li rel="/themes/qut/images/rdf-home-small.jpg" class="position-1 0 Yes" id="promo-id-245427">

	  <a class="thumb normal" href="/" title="Research Data Finder"></a>
		 <img src="/themes/qut/images/rdf-home-small.jpg" width="220" height="105" alt=""> 
		 <span>Research Data Finder</span> 
	  
	  <div class="promo-content-holder hide">
		  <p class="promo-content 0">
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/scf-home-small.jpg" class="position-2 0 Yes" id="promo-id-264677"> 

	  <a class="thumb normal" href="/scf" title="Software Finder"></a>
	  
		<img src="/themes/qut/images/scf-home-small.jpg" width="220" height="105" alt=""> 
		<span>Software Finder</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
<#else>

	<li rel="/themes/qut/images/scf-home-small.jpg" class="position-1 0 Yes" id="promo-id-245427">

	  <a class="thumb normal" href="/scf" title="Software Finder"></a>
		 <img src="/themes/qut/images/scf-home-small.jpg" width="220" height="105" alt=""> 
		 <span>Software Finder</span> 
	  
	  <div class="promo-content-holder hide">
		  <p class="promo-content 0">
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/spatial-home-small.jpg" class="position-2 0 Yes" id="promo-id-264677"> 

	  <a class="thumb normal" href="/spatial" title="Spatial Data Finder"></a>
	  
		<img src="/themes/qut/images/spatial-home-small.jpg" width="220" height="105" alt=""> 
		<span>Spatial Data Finder</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>

	<li rel="/themes/qut/images/people.jpg" class="position-1 0 Yes" id="promo-id-245427">

	  <a class="thumb normal" href="/people#http://www.qut.edu.au/ontologies/vivoqut#researcher" title="People and Groups that have generated research datasets"></a>
		 <img src="/themes/qut/images/people.jpg" width="220" height="105" alt=""> 
		 <span>People & Groups</span> 
	  
	  <div class="promo-content-holder hide">
		  <p class="promo-content 0">
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/activities.jpg" class="position-2 0 Yes" id="promo-id-264677"> 

	  <a class="thumb normal" href="/activities" title="Research Projects that have generated research datasets"></a>
	  
		<img src="/themes/qut/images/activities.jpg" width="220" height="105" alt=""> 
		<span>Projects</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/collections.jpg" class="position-3 0 Yes" id="promo-id-264874"> 

	  <a class="thumb normal" href="/dataCollections" title="Data Collections created or collected by QUT researchers"></a>
		<img src="/themes/qut/images/collections.jpg" width="220" height="105" alt=""> 
		<span>Data Collections</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>
	<li rel="/themes/qut/images/services.jpg" class="position-4 0 Yes" id="promo-id-266134"> 

	  <a class="thumb normal" href="/services" title="Software and Equipment that have generated research data"></a>
		<img src="/themes/qut/images/services.jpg" width="220" height="105" alt=""> 
		<span>Equipment & Services</span> 

	  <div class="promo-content-holder hide">
		  <p class="promo-content 0 youtube">    
		  </p>
	  </div>

	</li>

</#if>
</ul>

	-->
</div>


				
					
				</div>
		
		</div>  
		<#--  
			<@allClassGroups vClassGroups! /> 
		  -->
		</div>
      
            
         
           <#--  
			<section id="intro" role="region">
                <h1>QUT Research Data Finder</h1>
                
                 <p>Research Data Finder has been developed for the aggregation of metadata relating to research datasets and data collections generated by research at Queensland University of Technology. Part of the metadata stored within Research Data Finder is contributed to <a href="http://services.ands.org.au/home/orca/rda/">Research Data Australia</a>, a national portal for the discovery of research datasets and collections.</p>
			</section>
        	-->
        <#include "footer.ftl">
    </body>
</html>